floatUI.js
初步分析，原因应该是：
getPTList是按照控件左边缘来找到Pt控件的，只有满足特征（+号）而且左边缘最靠右的会入选，否则认为可能不是Pt控件（比如，恶搞玩家名）而排除。
但是，某些环境下，屏幕显示范围之外的Pt控件，左边缘横坐标是最靠右的，比正常显示出来的还要靠右，所以就导致显示范围内的Pt控件错误地被排除了。
所以解决方法就是另找一个左边缘横坐标参照，我觉得“请选择支援角色”文本控件就可以，不过还没测试。
=> 尝试修正少数手机无法选择助战的问题

floatUI.js
看上去在比较卡顿的机器上，可能是因为助战出现太慢，所以脚本错以为助战还没出现，于是就把助战错当作关卡坐标点击了。
#26 并没有完全修正这个问题，现在再次尝试修正
*之前觉得在state切换到STATE_SUPPORT后，在完成嗑药后还需要等待“请选择支援角色”出现，现在感觉这个应该没必要*
=> 尝试点击关卡坐标或关卡名称后检测是否出现嗑药窗口，如果出现就切换到助战选择状态

floatUI.js, main.js
合并 #39 #41 #42 #43 #45 #46 #47 #49 #50
增加重写的坐标转换（包括根据转屏方向修正刘海屏参数）；
稳定模式改名为防断线模式并支持新版周回脚本；
点击再战按钮时使用已知坐标进行换算（否则分辨率小于16:9的屏幕会点不到再战按钮）；
重写区服检测
*防断线模式目前局限性很大，目前发现只有战斗开始或结束（正要开始结算）的时候才能直接重连，否则只会被强制重新登录回首页*
*原先这些改动放在 #39 ，重新整理后改为放在这里*
=> （全部合并）重写坐标转换并支持防断线模式

floatUI.js
加这个toast主要是今天有人误解了“Shizuku未授权”这个toast的意思（他以为问题出在一个叫“Shizuku”的不知道是啥的东西身上，但实际情况应该是模拟器没开root权限，然后su执行命令蛋疼阻塞了，而且没有弹出root授权申请窗口）
-----
其实我还有一些想法：
1. Shizuku目前是没有toast通知提示的，所以不会干扰截屏，这一点也许需要告知用户
2. 可以浏览器弹出对应的下载链接，尤其是Android 5环境需要用旧版Shizuku
但目前先不管这么多……
=> Android 7.0以下第一次使用root权限时toast提示用户

floatUI.js
在这个改动之前，其实是忽略了limit.drug1/2/3，只看limit.drug1/2/3num是否为0来顺带检查嗑药设置是否启用。因为嗑药数量不会永久保存，而且点击嗑药复选框时已经会正确设置limit.drug1/2/3/4num，所以之前也可以正常工作。
保险起见，还是在isDrugEnough这里检查一下limit.drug1/2/3。
=> 让isDrugEnough在日志中更清晰地打出回复药状态；如果limit.drugX未启用则返回false

floatUI.js
Android 9或以上，但屏幕没有刘海的情况下getDisplayCutout()就会返回null
=> 避免getDisplayCutout()返回null时崩溃

floatUI.js, main.js
自己用了几天，效果还不错。反正也没几天了，没考虑各种兼容性，放上来先用着吧。独立脚本也不会影响其它的代码。
原理很简单，每隔一段时间杀掉一次游戏，等十几秒让系统自动回收内存，然后再重开进入剧情1自动续战。
在选人选关战斗首页开都可以，就是开了之后不能有其它操作。
=> 【活动内存爆炸临时方案】自动重开刷活动门票脚本

floatUI.js
这其实是 #47 忘了改的地方（捂脸）……
1. 在getAP中调用matchAll和findAll时，wait都设为false，否则仍然可能会无限制地等下去
2. 照搬waitAny等函数的写法
--------
在 #47 之前getAP是阻塞的，而且只有refillAP()里的一个地方有调用。
改这个是为了给以后自动重启游戏、自动登录做准备，用来检测是不是已经成功登录，我觉得能检测AP的话就说明已经登录进游戏了（虽然未必是在主页）。即便之前还有未完成战斗，也可以点击继续战斗按钮，然后战斗还是迟早结束（如果自动战斗启用的话）。
因为检测不到AP的时候（应该是还没点击屏幕到成功登录进主页）还需要点击屏幕，所以不能让他永远阻塞，需要设一个超时。
=> 修正：让getAP函数接受等待时间参数

floatUI.js
直接设置第二个参数root为true在某些模拟器上可能无法弹出授权窗口,或者即便弹出了也无法点允许
*很奇怪，同样是直接设置第二个参数root为true，改成app启动时就申请root，在MuMu上貌似反倒又没问题了*
=> app启动时就检测root或adb权限；增加privShell等函数，如果仍然没权限就再次申请

floatUI.js, main.js
“稳定模式”下控件信息抓取不全，比如`id`为`android:id/content`的控件就抓不到（实际上存在，关闭“稳定模式”就又可以抓到），然后就导致STATE_TEAM迟迟不会切换到STATE_BATTLE
=> 拒绝在无障碍服务抓取模式为压缩（也就是“稳定模式”）下运行脚本

floatUI.js
在log里有发现明明是Android 9以上（Android 11）却仍然时不时就未能成功获取到刘海屏参数的情况
（其实这里说的是getDisplayCutout没获取到的情况，这个时候其实一般问题也不大，因为还可以通过游戏FragmentView来推算刘海信息）
```
2021-06-26 20:55:34.183/DEBUG: 执行 副本周回（剧情，活动通用） 脚本
2021-06-26 20:55:34.242/DEBUG: 区服 zh_Hans
2021-06-26 20:55:34.252/DEBUG: detected_screen { width: 2340, height: 1080, type: 'wider' } detected_gameoffset { x: 210, y: 0, center: { y: 0 }, bottom: { y: 0 } }
2021-06-26 20:55:34.579/DEBUG: EditText bounds Rect(255, 0 - 2175, 132)
2021-06-26 20:55:34.580/DEBUG: detected_gamebounds Rect(255, 0 - 2175, 1080)
2021-06-26 20:55:34.581/DEBUG: currentRotation 1 initialRotation 0
2021-06-26 20:55:34.581/DEBUG: relativeRotation 1
2021-06-26 20:55:34.583/DEBUG: safeInsets before rotation { Left: 0, Top: 90, Right: 0, Bottom: 0 }
2021-06-26 20:55:34.585/DEBUG: …
```
=> 脚本启动时另开一个线程反复检测刘海屏参数,4秒后超时退出

floatUI.js
在MIUI 12.5上发现这个问题，不知道别的环境是什么样
有的时候返回的是转屏后的分辨率，有的时候不是，于是就导致故障，包括脚本选择悬浮窗窝在左下角显示不全、点击坐标捕获悬浮窗只覆盖屏幕半边等等。
解决方法就是脚本启动时记录一个初始的屏幕宽高值和转屏方向，后续调用时根据当前转屏方向来旋转屏幕宽高值。
#78 其实很大程度上就是这个问题导致的。
=> 修正getWindowSize搞错转屏方向的问题

main.js
如果/sdcard/auto_magireco/里有其他不是快照的东西就会触发
```
2021-07-14 23:03:54.225/ERROR: Thread[main,5]: Cannot convert null to boolean (main.js#245)
Cannot convert null to boolean
at reportBug (main.js:245:0)
```
=> 修正报告问题崩溃的问题

floatUI.js
2021-08-06晚上接到一个奇怪的反馈，称当时游戏在助战选择界面，脚本不动了。日志（见后）里看到点击AP按钮弹出AP药选择窗口似乎没有成功。很遗憾当时没有留下控件快照。
这个问题的情况还不是很清楚。不过想了想还是决定把refillAP里的`ap_refill_title_attempt_max`从1500改小到50。这个循环内每一轮都等待0.2秒，每5轮循环才点击一次，于是就约等于每1秒才尝试点击一次。
一般认为点开AP药选择窗口不会出什么问题（经过测试，即便暂时断网，游戏里点击AP按钮也仍然可以照常打开AP药选择窗口），但万一这里出了幺蛾子，应该也不需要反复重试等待5分多钟（1500*0.2s=300s=5min），而且如果直接停止线程退出脚本运行了，也就不能自动重开了。所以，这里就改成不退出，于是万一出了幺蛾子也可以交给自动重开来解决（检测到闪退，或者检测到卡在同一个状态时间太久）。
```
021-08-05 21:42:00.526/DEBUG: 更新参数： drug1 true
2021-08-05 21:42:00.536/DEBUG: 更新参数： drug1num 
2021-08-05 21:42:01.106/DEBUG: 更新参数： drug2 true
2021-08-05 21:42:01.117/DEBUG: 更新参数： drug2num 
2021-08-05 21:42:07.678/DEBUG: 保存参数： useAuto true
2021-08-05 21:42:07.682/DEBUG: 更新参数： useAuto true
2021-08-05 21:42:15.571/DEBUG: 更新参数： apmul 2
2021-08-05 21:43:05.083/DEBUG: 保存参数： justNPC true …
```
=> 尝试点开AP药选择窗口的最大检测次数改为50次,而且多次失败后不直接停止脚本运行

floatUI.js
偶尔isGameDead会出现奇怪的“误判”:
游戏看上去还在运行,脚本却检测不到它在前台,而且游戏可能是黑屏假死状态,动弹不得。然后就死循环了，启动游戏也启不起来，也不会再杀进程。
为尽量避免这个问题,这里进行“补刀”。
=> 在周回或重放时检测到闪退后补刀再杀一次进程

floatUI.js
#167 不小心引入了bug，导致isGameDead里的掉线检测失效了，现在修正。
除此之外，掉线的时候还可能是出现“发生错误”弹窗，这种弹窗之前不在检测范围内。
=> 修正isGameDead/reLogin/detectInitialState中掉线检测失效/不全面的bug

floatUI.js
因为 #214 目前暂时的想法是新发布一个基于识图的脚本，主要精力也转移过去，旧的基于无障碍的脚本可能不太顾得着了。
----------------
马上还是要重写一个基于识图的助战选择。
但现有的助战选择也可以留下来作为识图用不了时的后备选项。
----------------
有些玩家的支援队伍里，部分属性并没有设定角色，于是切到那个属性后，列表里就会出现一个不可点击的“未设定”助战。
在控件列表中，这个“未设定”助战没有Lv/HP/ATK/DEF，但是有Rank、有上次登录时间、有Pt。
1. 如果“未设定”插入到NPC后，就会导致NPC助战被错判成玩家助战。脚本假设NPC助战没有Rank和登录时间，只有玩家助战有这两项，然后就从NPC的Lv/HP/ATK/DEF开始往后搜索到了“未设定”的Rank和登录时间，于是就误以为这不是NPC而是个玩家。
2. 如果“未设定”插入到玩家后，就会导致搞错Pt加成。比如，本来是互关好友+60Pt，如果有个单fo“未设定”好友+20Pt插入到这个互关好友后面，因为脚本（为了避免碰到类似“+60”这种恶搞玩家名）是倒着搜寻Pt控件的，于是就先碰到了“未设定”插入进来的+20Pt，把+60Pt误识别成+20Pt。
=> 修正现有助战选择没考虑“未设定”的问题

floatUI.js, main.js
如果没有开启防断线模式（打输了=>在询问是否碎钻复活的界面傻等=>触发假死自动重开=>重新登录，其实是SL了，询问是否恢复战斗=>脚本自动点击恢复战斗=>再次打输=>再次询问是否碎钻复活，然后同下文）；或者抛开防断线模式不谈，恰巧碰上了重开游戏后需要恢复战斗、恢复战斗后又打输了的情况，因为脚本没有识图、是闭着眼点击恢复战斗按钮所在的位置，这个位置正好和碎钻复活确认按钮重合，所以就会痛失5魔法石。然后（预计）就会（因为碎钻后游戏内建自动战斗会自动停用）进入傻等玩家点击行动盘=>玩家没点击，触发假死自动重开=>恢复战斗=>傻等玩家点击行动盘=>玩家没点击，触发假死自动重开的蛋疼死循环……
=> 避免重新登录时误触碎钻复活确认按钮；定时杀进程增加考虑尽量不打断战斗

floatUI.js
优选助战列表如果留空了，如hint所述，是“不进行优选”、关闭这个功能的意思。
然而实际上如果开启了“只对优选助战使用官方自动续战”，就实质上变成了“停用官方自动续战”，即便开启了“优先使用官方自动续战”，也仍然不会点击自动续战按钮。这个和直觉与软件界面上的描述都不符。
所以这里就修正一下。
=> 如果在勾选启用只对优选助战使用官方自动续战的情况下又对助战优选列表留空,则认为可以启用官方自动续战(前提是开启了官方自动续战)

floatUI.js
```
2021-10-08 08:01:03.586/DEBUG: 已完成这一轮的所有战斗
2021-10-08 08:01:03.820/DEBUG: 点击断线重连按钮所在区域
2021-10-08 08:01:03.902/DEBUG: 使用无障碍服务模拟点击坐标 586,500
2021-10-08 08:01:04.056/DEBUG: 点击完成
2021-10-08 08:01:05.495/DEBUG: 点击断线重连按钮所在区域
2021-10-08 08:01:05.771/DEBUG: 使用无障碍服务模拟点击坐标 586,500
2021-10-08 08:01:05.925/DEBUG: 点击完成
2021-10-08 08:01:07.599/DEBUG: 点击断线重连按钮所在区域
2021-10-08 08:01:07.812/DEBUG: 使用无障碍服务模拟点击坐标 586,500
2021-10-08 08:01:07.970/DEBUG: 点击完成
2021-10-08 08:01:09.098/DEBUG: 已退出战斗结算界面,再等待10秒...
2021-10-08 08:01:19.761/DEBUG: 点击区域10
2021-10-08 08:01:19.899/DEBUG: 使用无障碍服务模拟点击坐标 1012,154
2021-10-08 08:01:20.058/DEBUG: 点击完成
2021-10-08 08:01:21.221/DEBUG: 区域10出现了,而且确定/开始按钮没有出现,重新检测状态
2021-10-08 08:01:21.481/DEBUG: 点击区域10
2021-10-08 08:01:21.602/DEBUG: 使用无障碍服务模拟点击坐标 1012,154
2021-10-08 …
```
=> 理子脚本:尝试解决某OPPO真机大概率在点击区域后不能继续点确定的问题

floatUI.js
Fix #208
1. 一开始发现`getDefaultDisplay().getSize()`可能（概率性）返回横竖屏方向错误的数据（ #89 #110 等等），当时就导致了悬浮窗（概率性）显示异常，尤其是capture捕获点击坐标受影响最大，只能覆盖左半个屏幕（如果只看这一个问题，刚刚才意识到其实有很简单的解决办法 #273 ，但问题不仅限于此，比如脚本选择悬浮窗也会显示不正常，内容挤在屏幕左边、而且下面还会超出屏幕显示范围之外）。
2. 搜索研究后，找到了模仿`wm size`命令（`getInitialDisplaySize`）来获取“自然转屏方向”下屏幕分辨率数据的方法，然后，据此修改了`getWindowSize`函数，配合`getDefaultDisplay().getRotation()`貌似就解决了转盘方向不对的问题（ #164 ）。但这样又导致刘海屏下，悬浮窗靠右时，会（因为没考虑刘海扣除的X轴距离）而超出屏幕范围（ #208 ）。
3. 于是现在就只能用这个很hack、而且会导致悬浮窗调用getX/setPosition时X轴方向反转的办法了。
=> 修正刘海屏横屏下悬浮窗靠右时超出屏幕范围的问题

floatUI.js, main.js, project.json
```
2021-10-17 09:40:15.140/DEBUG: 重新登录...
2021-10-17 09:40:18.571/DEBUG: 点击OK按钮区域...
2021-10-17 09:40:18.578/DEBUG: 使用Shizuku模拟点击: [960,769]
2021-10-17 09:40:20.116/DEBUG: 使用Shizuku模拟点击: [960,769] 完成
2021-10-17 09:40:20.117/DEBUG: 点击OK按钮区域完成,等待1秒...
2021-10-17 09:40:21.118/DEBUG: 点击战斗已结束OK按钮区域...
2021-10-17 09:40:21.163/DEBUG: 使用Shizuku模拟点击: [960,660]
2021-10-17 09:40:22.379/DEBUG: 使用Shizuku模拟点击: [960,660] 完成
2021-10-17 09:40:22.386/DEBUG: 点击战斗已结束OK按钮区域完成,等待1秒...
2021-10-17 09:40:28.614/DEBUG: 游戏已经闪退
2021-10-17 09:40:28.622/DEBUG: 检测到游戏再次闪退,无法继续登录
2021-10-17 09:40:28.622/DEBUG: 已恢复上次的选关动作录制数据
2021-10-17 09:40:38.487/DEBUG: 使用Shizuku执行shell命令: [runbg() { "/data/local/tmp/auto_magireco_fatal_killer.sh" > /dev/null & }; runbgbg() { runbg & }; runbgbg & exit;
] 完成
2021-10-17 …
```
=> 【6.0.4】避免updateUI因为无障碍抽风而崩溃

floatUI.js
为了解决报毒问题，AutoJS Pro V9 内测版 9.0.11-0 混淆了类名和activity名。现在根据引擎版本号决定用哪个activity名，于是v8和v9环境就都能正常打开自己的设置界面了。
=> 修正AutoJSPro v9混淆activity名后脚本不能打开自己的设置界面
