- floatUI.js
> 悬浮窗使用本地图标文件

- floatUI.js
- main.js
照顾text/desc、字符串是否拆开等一共2×2=4种情况
> 重写AP检测、助战选择（Pt检测）；小改嗑药、周回

- floatUI.js
https://github.com/cjwhkl2008hh/magireco_autoBattle/pull/2/files
> 控件text不仅可能是空字符串，还可能是null，这种情况下也从desc取值

- floatUI.js
#34 似乎仍然没有避免抛出异常
```
2021-06-13 06:13:16.372/DEBUG: 使用Shizuku模拟点击坐标 1696,971
2021-06-13 06:13:17.049/DEBUG: 模拟点击完成
2021-06-13 06:13:17.664/DEBUG: 结算完成
2021-06-13 11:55:59.065/ERROR: Thread[main,5]: TypeError: Cannot call method "refresh" of null (file:/data/data/top.momoe.auto/files/project/floatUI.js#1341)
TypeError: Cannot call method "refresh" of null
at findID (file:/data/data/top.momoe.auto/files/project/floatUI.js:1341:0)
at taskDefault (file:/data/data/top.momoe.auto/files/project/floatUI.js:1950:0)
2021-06-13 11:56:16.050/DEBUG: 停止脚本
```
https://github.com/segfault-bilibili/magireco_autoBattle/blob/286009e435e84c24cd34e3a56f81fabb05f04841/floatUI.js#L1341
> 再次尝试避免在auto.root == null时抛出异常使脚本崩溃

- main.js
https://github.com/cjwhkl2008hh/magireco_autoBattle/pull/1
> 在线更新URL中指定版本号；把engines.stopAll放在后面

- floatUI.js
> 避免每次在选助战时调用APrefill的过程中多余的2秒的等待(仍然会等0.2秒)

- floatUI.js
> 避免嗑药窗口关闭太慢，导致getPTList检测不到“请选择支援角色”然后崩溃的问题

- floatUI.js
> 修正方块屏点不到关闭AP回复窗口按钮

- floatUI.js
> 在STATE_REWARD_POST使用getAP替代match(/\d*\/\d*/)

- floatUI.js
（捂脸）
忘记加的话会导致以字符串形式相加，然后调用find等函数时的等待时间就约等于永久了。
> 给部分limit.timeout补上忘记加的parseInt

- floatUI.js
- main.js
- project.json
把 #69 #70 #71 #72 #73 #74 #75 #76 #77 #78 #80 #81 全部合并到一起
> 【全部合并】4.1.0

- floatUI.js
- main.js
主要是防止误触：比如在自动重开的时候游戏又闪退了，然后误点到脚本自己的设置界面，本来不想碎钻的变成启用碎钻了，然后就肉疼了……
> 监控脚本运行状态；有脚本运行时锁定UI；线程结束时也同时关闭对话框

- floatUI.js
getWindowSize在带鱼屏上的范围其实比游戏画面还宽，所以就导致点击右上角的动作实际上点到了游戏画面外的虚空，无效了。
> 在click、swipe、findPopupInfoDetailTitle中改用getFragmentViewSize替代getWindowSize

- floatUI.js
- main.js
- project.json
合并 #44 #82 #84 #85 #86 #88 #89
> 【全部合并】4.2.0

- floatUI.js
- main.js
> （赶工完成）移植魔改版镜层自动战斗

- floatUI.js
在 #135 基础上修正这个问题
目前是杜鹃花型活动 三日月庄的summer vacation
> 修正getCostAP在文字和数字没拆开时无法检测AP消耗量的问题

- floatUI.js
- main.js
> 结算时弹窗是否关注路人时默认点是关注,可配置成不关注

- floatUI.js
> 在队伍调整界面先闭着眼点开始或自动续战按钮再开始检测弹窗和按钮

- floatUI.js
> 不再弹窗询问是否要测试助战自动选择;toast提示正在测试助战自动选择并把等待间隔缩短到4秒

- floatUI.js
> 在getWindowSize/getRotation可能返回错误结果(竖屏)时toast警告

- floatUI.js
修正杜鹃花型活动支持(普通周回/自动重开);
删除一些多余的tips文字;
重放动作时可以从文件读取;
改进toast提示文字以避免误解;
开始周回时可以选择停用自动重开
> 修正杜鹃花型活动支持(普通周回/自动重开)

- floatUI.js
- main.js
- project.json
合并 #133 #161 #162 #163 #164 #165 #167 #168 #170 #172 #173
> 【全部合并】5.3.0

- floatUI.js
> 检测录屏API是否返回了空白图像

- floatUI.js
```
2021-08-08 18:04:33.079/DEBUG: 等待AP药选择窗口出现...
2021-08-08 18:04:33.299/DEBUG: 点击AP按钮
2021-08-08 18:04:33.454/DEBUG: 使用无障碍服务模拟点击坐标 1077,56
2021-08-08 18:04:33.610/DEBUG: 点击完成
2021-08-08 18:04:33.818/DEBUG: 等待AP药选择窗口出现...
2021-08-08 18:04:34.059/DEBUG: AP药选择窗口已经出现
2021-08-08 18:04:34.894/DEBUG: 
第1种回复药
已启用
剩余:    57个
个数限制:NaN个
2021-08-08 18:04:34.895/DEBUG: 点击使用第1种回复药
2021-08-08 18:04:35.000/DEBUG: 使用无障碍服务模拟点击坐标 439,671
2021-08-08 18:04:35.154/DEBUG: 点击完成
2021-08-08 18:04:35.250/DEBUG: 点击使用第1种回复药
2021-08-08 18:04:35.517/DEBUG: 使用无障碍服务模拟点击坐标 439,671
2021-08-08 18:04:35.672/DEBUG: 点击完成
2021-08-08 18:04:35.879/DEBUG: 点击使用第1种回复药
2021-08-08 18:04:36.065/DEBUG: 使用无障碍服务模拟点击坐标 439,671
2021-08-08 18:04:36.220/DEBUG: 点击完成
...
2021-08-08 20:14:53.982/DEBUG: AutoBattle v5.4.0
2021-08-08 …
```
> 点击三种AP回复药按钮时使用硬编码的坐标

- floatUI.js
- main.js
> 可选不再询问是否自动重开；默认开启假死检测超时和无条件定时杀进程重开

- floatUI.js
> 替代sync()来避免不同函数占有同一个锁的问题

- floatUI.js
- main.js
- project.json
> 【全部合并】5.6.0

- floatUI.js
- main.js
- project.json
> 【全部合并】5.8.0

- floatUI.js
- main.js
- project.json
> 【全部合并】5.8.1

- floatUI.js
- main.js
- project.json
> 【全部合并】5.9.1

- floatUI.js
- main.js
- project.json
> 【全部合并】5.9.2

- floatUI.js
- main.js
- project.json
> 【全部合并】5.9.3

- floatUI.js
> 在启用闪退自动重开时提醒同时开启防断线模式

- floatUI.js
> 理子活动在杀进程后也重置battleStartTime

- floatUI.js
> 提醒用户脚本列表不止眼前这几个选项,还可以继续往下拖动;扩大悬浮窗大小并调整布局(显示边框)

- floatUI.js
> 理子活动脚本也要求测试闪退重开

- floatUI.js
> 让clickReconnect每次调用只进行一次点击动作

- floatUI.js
> 修正root权限检测；Android 5下不再提示下载老版本的Shizuku 3.6.1

- floatUI.js
> 使用root权限截屏时也检查图片是不是空白
